[project]
name = "crosslingual-rule-following"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.0",
    "eap[viz]",
    "huggingface-hub>=1.24.0",
    "kneed[plot]>=0.8.6",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "pygraphviz>=2.0.1",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "torch>=2.13.0",
    "tqdm>=4.69.1",
    "transformer-lens>=3.5.1",
]

[tool.uv.sources]
eap = { git = "https://github.com/hannamw/EAP-IG.git" }
